config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root "welcome#index"

  resources :users do
    resources :task_lists do
      resources :tasks do
        member do
          patch :complete
        end
      end
    end
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_lists
  
  def completed?
    !completed_at.blank?
  end

end

app/models/task_list.rb
class TaskList < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :task_lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
    if User.exists?(session[:user_id])
      @current_user = User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def after_sign_in_path_for(current_user)
    user_task_lists_path(current_user)
  end
end

app/controllers/task_lists_controller.rb
class TaskListsController < ApplicationController
  before_action :set_task_list, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @user = User.find(params[:user_id])
    @task_lists = @user.task_lists
  end

  def new
    @user = User.find(params[:user_id])
    @task_list = TaskList.new
  end

  def create
    @user = User.find(params[:user_id])
    @task_list = @user.task_lists.create!(task_list_params)

    if @task_list.save
      redirect_to user_task_list_path(@user, @task_list), notice: 'Tasklist successfully created.'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @task = Task.new
  end

  def edit
    @user = User.find(params[:user_id])
    @task_list = @user.task_lists.find(params[:id])
  end

  def update
    if @task_list.update(task_list_params)
      redirect_to user_task_list_url, notice: 'Tasklist successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @task_list.destroy
    redirect_to user_task_lists_path, notice: 'Tasklist successfully deleted.'
  end

  private

  def set_task_list
    @task_list = TaskList.find(params[:id])
  end

  def task_list_params
    params.require(:task_list).permit(:title, :description)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task_list

  def index
    @user = User.find(params[:user_id])
    @tasks = @user.tasks
  end

  def new
    @user = User.find(params[:user_id])
    @task = Task.new
  end

  def create
    @task = @task_list.tasks.create(task_params)
    redirect_to user_task_list_url(@user, @task_list)
  end

  def show
  end

  def edit
    @user = User.find(params[:user_id])
    @task = @user.tasks.find(params[:id])
  end

  def update
    if @task.update(task_params)
      redirect_to user_tasks_url
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @task = @task_list.tasks.find(params[:id])
    @task.destroy
    redirect_to user_task_list_url(@user, @task_list), notice: 'Task was successfully deleted.'
  end

  def complete
    @user = User.find(params[:user_id])
    @task = @task_list.tasks.find(params[:id])
    @task.update_attribute(:completed_at, Time.now)
    redirect_to user_task_list_url(@user, @task_list), notice: 'Task completed.'
  end

  private

  def set_task_list
    @user = User.find(params[:user_id])
    @task_list = TaskList.find(params[:task_list_id])
  end

  def task_params
    params.require(:task).permit(:content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    @current_user = @user
    redirect_to user_task_lists
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/task_lists_helper.rb
module TaskListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>UnDone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Font Awesome for icons -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
  <nav class="navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "UnDone", root_path, class: "navbar-brand" %>
      </div>
      <ul class=" nav nav-pills navbar-right">
        <% if current_user %>
        <li> <%= link_to "Create New List", new_user_task_list_path(current_user) %></li>
        <li> <%= link_to 'My Lists', user_task_lists_path(current_user) %></li>
        <li>  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li>  <%= link_to "Sign Up", new_user_registration_path %></li>
        <li>  <%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <%= yield %>

</body>
</html>

app/views/task_lists/_form.html.erb
<%= simple_form_for [@user, @task_list] do |f| %>

<p>
  <%= f.input :title, label: 'Title' %> <br>
  <%= f.input :description, label: 'Description' %>
</p>

<p>
  <%= f.button :submit %>
</p>

<% end %>

app/views/task_lists/edit.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h1> Edit List </h1>
    <%= render 'form' %>
    <%= link_to 'Cancel', user_task_list_path %>
</div>

app/views/task_lists/index.html.erb
<p id="notice"><%= notice %></p>

<div class="body-container">


<% @task_lists.each do |task_list| %>
  <div class="index clearfix">
    <h2 class="list-title"><%= link_to task_list.title, user_task_list_path(@user, task_list) %></h2>
    <p class="list-sub-title"><%= task_list.description %></p>
  </div>
<% end %>

<div class="links">
  <%= link_to "Create New List", new_user_task_list_path %>
</div>
</div>

app/views/task_lists/new.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h1> New List </h1>
  <%= render 'form' %>
  <%= link_to 'Cancel', user_task_lists_path(@user) %>
</div>

app/views/task_lists/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-lg-6 col-lg-offset-3">
  <h1> <%= @task_list.title %> </h1>
  <p> <%= @task_list.description %> </p>

  <div id="tasks-wrapper">
    <% @task_list.tasks.each do |task| %>
    <%= render partial: "tasks/task", locals: {task: task} %>
    <% end %>
    <div id="form">
      <%= render "tasks/form" %>
    </div>
  </div>

  <%= link_to '<<Back', user_task_lists_path %> |
  <%= link_to 'Edit List', edit_user_task_list_path %> |
  <%= link_to "Delete List", user_task_list_path(@user, @task_list.id), method: :delete, data: { confirm: "are you sure?" } %>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for [@user, @task_list, @task_list.tasks.build] do |f| %>
  <%= f.text_field :content, placeholder: 'New Task' %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row clearfix">
  <% if task.completed? %>
  <div class="completed">
    <%= link_to complete_user_task_list_task_path(@user, @task_list, task.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
    <% end %>
  </div>
  <div class="task">
    <p style="opacity: 0.4;"><strike><%= task.content %></strike></p>
  </div>
  <div class="delete">
    <%= link_to user_task_list_task_path(@user, @task_list, task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
    <% end %>
  </div>
  <% else %>
  <div class="completed">
    <%= link_to complete_user_task_list_task_path(@user, @task_list, task.id), method: :patch do %>
    <i class="fa fa-check"></i>
    <% end %>
  </div>
  <div class="task">
    <p><%= task.content %></p>
  </div>
  <div class="delete">
    <%= link_to user_task_list_task_path(@user, @task_list, task.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
    <% end %>
  </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h1> Edit Your Task </h1>
    <%= render 'form' %>
    <%= link_to 'Cancel', user_tasks_path %>  
</div>

app/views/tasks/index.html.erb
<% if current_user %>
  <% @tasks.each do |task| %>

  <% if task.completed? %>

  <div class="container">
      <div class="col-lg-6 col-lg-offset-1">

      <div class='col-md-6'>
        <h2 style="opacity: 0.5;"><strike><%= link_to task.title, user_task_path(@user, task) %></strike></h2>
        <p style="opacity: 0.5;"><strike><%= task.content %></strike></p>
        <p "opacity: 0.5;">Completed: <%= time_ago_in_words(task.completed_at)%> ago</p>
      </div>

      <div class='col-md-2'>
        <p><%= link_to edit_user_task_path(@user, task) do %></p>
        <i class="fa fa-lg fa-edit"></i>
        <% end %>
      </div>

      <div class='col-md-2'>
        <p><%= link_to complete_user_task_path(@user, task), method: :patch do %></p>
        <i class="fa fa-lg fa-check"></i>
        <!-- Nice FontAwesome-ing -->
        <% end %>
      </div>

      <div class='col-md-2'>
        <p><%= link_to user_task_path(@user, task), method: :delete, data: {confirm: "Are you sure?"} do %></p>
        <i class="fa fa-lg fa-trash"></i>
        <% end %>
      </div>

      </div>
    </div>

    <% else %>

    <div class="container">
        <div class="col-lg-6 col-lg-offset-1">
          <div class='col-md-6'>
            <h2><%= link_to task.title, user_task_path(@user, task) %></h2>
            <p><%= task.content %></p>
            <p>Created: <%= time_ago_in_words(task.created_at)%> ago</p>
          </div>

          <div class='col-md-2'>
            <p><%= link_to edit_user_task_path(@user, task) do %></p>
            <i class="fa fa-lg fa-edit"></i>
            <% end %>
          </div>

          <div class='col-md-2'>
            <p><%= link_to complete_user_task_path(@user, task), method: :patch do %></p>
            <i class="fa fa-lg fa-check"></i>
            <% end %>
          </div>

          <div class='col-md-2'>
            <p><%= link_to user_task_path(@user, task), method: :delete, data: {confirm: "Are you sure?"} do %></p>
            <i class="fa fa-lg fa-trash"></i>
            <% end %>
          </div>
        </div>
    </div>

  <% end %>
  <% end %>
  <% end %>

app/views/tasks/new.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h1> New Task </h1>
  <%= render 'form' %>
  <%= link_to 'Cancel', user_tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="col-lg-6 col-lg-offset-3">
  <h1> <%= @task.title %> </h1>
  <p> <%= @task.content %> </p>
  <%= link_to '<<Back', user_tasks_path %>
</div>

app/views/users/edit.html.erb
<%= link_to 'Cancel', user_path %>

<h2>Edit Your Profile</h2>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Submit" %>
<% end %>

app/views/users/index.html.erb
<h2>Users</h2>
<ul>
  <% @users.each do |user| %>
  <li><%= link_to user.username, user %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for @user do |f| %>
<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
 <h2><%= @user.username %> <%= link_to "(edit)", edit_user_path(@user) %></h2>

app/views/welcome/index.html.erb
<div class="banner">
  <div class="banner-content" >
    <h1>UnDone</h1>
    <p> The app that helps you get organized, get it done, and get on with your life.</p>
    <p><%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-primary" %></p>
  </div>
</div>

<!-- How the UnDone App Works -->

<div class="container app-info">
  <div class="row">

    <div class="col-md-4">
      <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
      <h2>Sign Up</h2>
      <p> Not a member? Create an account to get started!</p>
    </div>

    <div class="col-md-4">
      <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
      <h2>Make a Tasklist</h2>
      <p>Create a single list for all your tasks or categorize them using multiple lists.</p>
    </div>

    <div class="col-md-4">
      <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
      <h2>Get Stuff Done</h2>
      <p>Easily complete or delete tasks once they're finished. Done with your entire list? You can delete lists too!</p>
    </div>

  </div>
</div>